heat_template_version: 2013-05-23
description: >
  Heat WordPress template, demonstrating Provider Resource.

parameters:
    user_key:
        type: string
        default: "The greate Rakesh"
        description : Name of a KeyPair to enable SSH access to the instance


resources:
  wordpress_instance:
    type: OS::Nova::Server
