heat_template_version: 2013-05-23
description: Random String templates

parameters:
    len:
        type: string
        default: 16
    salt:
        type: string
        default: "quickbrownfox"
    char_classes:
        type: string
        default: [{"class": "hexdigits", "min": 4}]

resources:
    my_res_group:
        type: OS::Heat::ResourceGroup
        properties:
            count: 200
            resource_def:
                type: OS::Heat::RandomString
                properties:
                    length: 32
                    salt: {get_param: salt}
                    character_classes: {get_param: char_classes}
