heat_template_version: 2013-05-23
description: Random String templates

parameters:
    len:
        type: string
        default: 16
    salt:
        type: string
        default: "quickbrownfox"
    char_classes:
        type: string
        default: [{"class": "hexdigits", "min": 4}]

resources:
    A:
        type: OS::Heat::RandomString
        properties:
            length: {get_param: len}
            salt: {get_param: salt}
            character_classes: {get_param: char_classes}

    B:
        type: OS::Heat::RandomString
        properties:
            length: 32
            salt: {get_param: salt}
            character_classes: {get_param: char_classes}

    C:
        type: OS::Heat::RandomString
        depends_on: [A, B]
        properties:
            length: {get_param: len}
            #length: 64
            salt: {get_param: salt}
            character_classes: {get_param: char_classes}
#    D:
#        type: OS::Heat::RandomString
#        depends_on: C
#        properties:
#            length: {get_param: len}
#            salt: {get_param: salt}
#            character_classes: {get_param: char_classes}
#
#    E:
#        type: OS::Heat::RandomString
#        depends_on: C
#        properties:
#            length: 32
#            salt: {get_param: salt}
#            character_classes: {get_param: char_classes}
    F:
        type: OS::Heat::RandomString
        depends_on: C
        properties:
            length: 64
            salt: {get_param: salt}
            character_classes: {get_param: char_classes}
