heat_template_version: 2016-04-08
description: |
  Template which creates single EC2 instance
parameters:
  key:
    type: string
  flavor:
    type: string
  image:
    type: string
  volume_size:
    type: number
    description: Size of the volume to be created.
    default: 1
    constraints:
      - range: { min: 1, max: 1024 }
        description: must be between 1 and 1024 Gb.
  subnet_cidr:
    type: string
  external_net:
    type: string
  dns_servers:
    type: comma_delimited_list
resources:
  volume:
    type: OS::Cinder::Volume
    properties:
      size: { get_param: volume_size }

  volume_attachment:
    type: OS::Cinder::VolumeAttachment
    properties:
      volume_id: { get_resource: volume }
      instance_uuid: { get_resource: instance }

  instance:
    type: OS::Nova::Server
    properties:
      image: { get_param: image }
      flavor: { get_param: flavor }
      key_name: { get_param: key }
      networks:
         - port: { get_resource: server_port }

  network:
    type: OS::Neutron::Net
    properties:
      name: network

  subnet:
    type: OS::Neutron::Subnet
    properties:
      network_id: { get_resource: network }
      name: subnet
      ip_version: 4
      cidr: { get_param: subnet_cidr }
      dns_nameservers: { get_param: dns_servers }

  router:
    type: OS::Neutron::Router
    properties:
      name: router
      admin_state_up: true
      external_gateway_info:
        network: { get_param: external_net }

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: {get_resource: router}
      subnet_id: {get_resource: subnet}

  server_port:
    type: OS::Neutron::Port
    properties:
      network: { get_resource: network }
      fixed_ips:
        - subnet_id: { get_resource: subnet }
      security_groups: [{ get_resource: security_group }]

  floating_ip:
    type: OS::Neutron::FloatingIP
    properties:
      floating_network: { get_param: external_net }
      port_id: { get_resource: server_port }

  security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: security_group
      description: Ping and SSH
      rules:
      - protocol: icmp
      - protocol: tcp
        port_range_min: 22
        port_range_max: 22
