heat_template_version: 2016-04-08

parameters:
  key_name:
    type: string
  instance_type:
    type: string
  image_id:
    type: string
  public_net:
    type: string
  dns_list:
    type: comma_delimited_list
  cidr:
    type: string
  instances_per_group:
    type: number
 
resources:
  server_group:
    type: OS::Heat::ResourceGroup
    properties:
      count: { get_param: instances_per_group }
      resource_def:
        type: server_with_vol_and_fip.yaml
        properties:
          key: { get_param: key_name }
          flavor: { get_param: instance_type }
          image: { get_param: image_id }
          external_net: { get_param: public_net }          
          subnet_cidr: { get_param: cidr }
          dns_servers: { get_param: dns_list }
