heat_template_version: 2013-05-23

description: >
  Heat WordPress template to support F18, using only Heat OpenStack-native
  resource types, and without the requirement for heat-cfntools in the image.
  WordPress is web software you can use to create a beautiful website or blog.
  This template installs a single-instance WordPress deployment using a local
  MySQL database to store the data.

parameters:
  key_name:
    type: string
    description : Name of a KeyPair to enable SSH access to the instance
    default: heat_key
  instance_type:
    type: string
    description: Instance type for WordPress server
    default: m1.tiny
    constraints:
      - allowed_values: [m1.tiny, m1.small, m1.medium, m1.large]
        description: instance_type must be one of m1.small, m1.medium or m1.large
  image_id:
    type: string
    description: ID of the image to use for the WordPress server
    default: cirros-0.3.2-x86_64-uec

resources:
  myserver:
    type: OS::Nova::Server
    properties:
      image: { get_param: image_id }
      flavor: { get_param: instance_type }
      key_name: { get_param: key_name }
      networks:
        - network: 64b75280-bd36-47b4-b0dc-05001182873f
